SineBuffer class
pyfar/haiopy pull request #8
Opened 2023-03-21 17:50 UTC by twennemann

# Discription
First draft of the SineBuffer class, which generates a sinewave with the length of `blocksize`. The `next()`-method increases the phase and calculates the next block.

#### Unclear:
I wasn't sure if the `next()` - method returns the current samples of the block or the next ones (because in SignalBuffer it takes the current index?!).

2023-03-22 10:42 UTC, mberz commented on haiopy/buffers.py
> +                               self._sampling_rate)
Let's use a pure numpy implementation here. pf.Signal creates to much overhead and CPU load.

2023-03-22 10:58 UTC, mberz requested changes
Thanks for drafting this!

As already discussed, a pure numpy array implementation instead of creating a pyfar.Signal in every iteration is much lighter on the CPU and probably the way to go here. We should keep this class as light-weight as possible

2023-03-22 10:58 UTC, mberz commented on haiopy/buffers.py
> +        return self._data.time
I'd return the data, without saving to _data here

2023-03-22 10:58 UTC, mberz commented on haiopy/buffers.py
> +        return self._phase
I'm not sure, but I'd say the getter does not need to check if the buffer is active, since phase is not a numpy array, isn't it?

2023-03-22 10:58 UTC, mberz commented on haiopy/buffers.py
> +        return self._data
```suggestion
```
I'd remove this. When using numpy arrays only it returns the same array as `next()`.

2023-03-22 10:58 UTC, mberz commented on haiopy/buffers.py
> +class SineBuffer(_Buffer):
```suggestion
class SineGenerator(_Buffer):
```

2023-03-27 09:29 UTC, mberz requested changes
Concept looks good so far, I've just had the idea to merge `next` and `_sine` functions to get rid of an additional function call. 
Let's go ahead and implement the tests :)

2023-03-27 09:29 UTC, mberz commented on haiopy/buffers.py
> +        self._data = self._sine()
```suggestion
```

2023-03-27 09:29 UTC, mberz commented on haiopy/buffers.py
> +        self._data = self._sine()
```suggestion
```

2023-03-27 09:29 UTC, mberz commented on haiopy/buffers.py
> +        return self._sine()
Can't we just merge these two functions?

```suggestion
    def next(self):
        """Return the next audio block as numpy array and increases the phase.
        """
        omega = 2 * np.pi * self._frequency
        data = self._amplitude * np.sin(
            omega*np.arange(self._blocksize)/self._sampling_rate + self._phase)
        self._phase += omega*(self._block_size / self._sampling_rate)
        return data
```

2023-06-15 08:14 UTC, mberz approved these changes
Looks good to me. Can we merge this, or is there a reason for this to be a "draft"?

2023-06-19 15:48 UTC, twennemann commented
> Looks good to me. Can we merge this, or is there a reason for this to be a "draft"?
No reason for the it to be a draft anymore. I think it's ready to merge, too.

2023-10-05 13:03 UTC, merged